version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: supportdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - db
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - WEBHOOK_PATH=/webhook
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  pgdata:
